name: Build Kaleidoswap App

on:
  push:
    branches:
      - dev
      - ci_cd
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.16.0'

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install system dependencies on Linux
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev libsoup2.4-dev libjavascriptcoregtk-4.0-dev libwebkit2gtk-4.0-dev

    - name: Install system dependencies on macOS
      if: matrix.os == 'macos-latest'
      run: |
        brew install openssl gtk+

    - name: Debug: Show OpenSSL installation paths on macOS
      if: matrix.os == 'macos-latest'
      run: |
        echo "OpenSSL is installed at: $(brew --prefix openssl)"
        echo "Listing OpenSSL include directory:"
        ls -l $(brew --prefix openssl)/include
        echo "Listing OpenSSL library directory:"
        ls -l $(brew --prefix openssl)/lib

    - name: Set OpenSSL environment variables on macOS
      if: matrix.os == 'macos-latest'
      run: |
        OPENSSL_PREFIX=$(brew --prefix openssl)
        if [ -d "$OPENSSL_PREFIX" ]; then
          echo "OPENSSL_DIR=$OPENSSL_PREFIX" >> $GITHUB_ENV
          echo "OPENSSL_INCLUDE_DIR=$OPENSSL_PREFIX/include" >> $GITHUB_ENV
          echo "OPENSSL_LIB_DIR=$OPENSSL_PREFIX/lib" >> $GITHUB_ENV
        else
          echo "Error: OpenSSL prefix not found."
          exit 1
        fi

    - name: Verify OpenSSL paths on macOS
      if: matrix.os == 'macos-latest'
      run: |
        echo "OpenSSL include directory: $OPENSSL_INCLUDE_DIR"
        echo "OpenSSL library directory: $OPENSSL_LIB_DIR"
        ls -l $OPENSSL_INCLUDE_DIR
        ls -l $OPENSSL_LIB_DIR

    - name: Install dependencies
      run: pnpm install

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Install Tauri CLI
      run: pnpm install --save-dev @tauri-apps/cli

    - name: Build Tauri app
      run: pnpm run tauri build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: tauri-artifacts-${{ matrix.os }}
        path: ./src-tauri/target/release/bundle/**

