name: Build Kaleidoswap App

on:
  push:
    branches:
      - dev
      - ci_cd
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.16.0'

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install system dependencies on Linux
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev libsoup2.4-dev libjavascriptcoregtk-4.0-dev libwebkit2gtk-4.0-dev

    - name: Install system dependencies on macOS
      if: matrix.os == 'macos-latest'
      run: |
        brew install openssl gtk+

    - name: Set OpenSSL environment variables on macOS
      if: matrix.os == 'macos-latest'
      run: |
        OPENSSL_PREFIX=$(brew --prefix openssl)
        if [ -d "$OPENSSL_PREFIX" ]; then
          echo "OPENSSL_DIR=$OPENSSL_PREFIX" >> $GITHUB_ENV
          echo "OPENSSL_INCLUDE_DIR=$OPENSSL_PREFIX/include" >> $GITHUB_ENV
          echo "OPENSSL_LIB_DIR=$OPENSSL_PREFIX/lib" >> $GITHUB_ENV
        else
          echo "Error: OpenSSL prefix not found."
          exit 1
        fi

    - name: Install MSVC Build Tools and OpenSSL on Windows
      if: matrix.os == 'windows-latest'
      run: |
        choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.VCTools --includeRecommended --includeOptional"
        choco install openssl

    - name: Set OpenSSL environment variables on Windows
      if: matrix.os == 'windows-latest'
      run: |
        $OPENSSL_PREFIX="C:\Program Files\OpenSSL"
          if (Test-Path $OPENSSL_PREFIX) {
            echo "OPENSSL_DIR=$OPENSSL_PREFIX" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
            echo "OPENSSL_INCLUDE_DIR=$OPENSSL_PREFIX\include" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
            echo "OPENSSL_LIB_DIR=$OPENSSL_PREFIX\lib" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
          } else {
            Write-Error "Error: OpenSSL directory not found."
            exit 1
          }

    - name: Install dependencies
      run: pnpm install

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Install Tauri CLI
      run: pnpm install --save-dev @tauri-apps/cli

    - name: Build Tauri app
      run: pnpm run tauri build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: tauri-artifacts-${{ matrix.os }}
        path: ./src-tauri/target/release/bundle/**
